Document: f-engrave
Title: Debian f-engrave Manual
Author: <insert document author here>
Abstract: This manual describes what f-engrave is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/f-engrave/f-engrave.sgml.gz

Format: postscript
Files: /usr/share/doc/f-engrave/f-engrave.ps.gz

Format: text
Files: /usr/share/doc/f-engrave/f-engrave.text.gz

Format: HTML
Index: /usr/share/doc/f-engrave/html/index.html
Files: /usr/share/doc/f-engrave/html/*.html
